name: GitHub Actions Demo 1
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [ push ]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: node -v
      - run: npm install pnpm -g
      - run: npm install -g typescript
      - run: tsc -v

